### ISSUE TITLE
Plots: average by age, gender over multiple output CSVs

### ISSUE THREAD

**Issue by jamesturner246** [imperialCHEPI/healthgps-plots#1]
The current R plotting script `Visualization.R` at https://github.com/imperialCHEPI/healthgps-plots takes in a fixed number of output CSV files and averages data over age and gender, weighted by group size, separated into baseline and intervention scenarios.

It would be useful to allow an arbitrary number of files to be fed in and averaged in this way. This would allow us to plot results from HPC array jobs, with multiple output files for each job array index.

as before, we should be careful to weight the average by `count` for each group, and ensure that baseline and intervention data points are separated correctly -- the ordering of baseline and intervention results is not guaranteed.

**Comment by jzhu20** [comment]
@TinyMarsh My updated R script can be found here, with commands to import multiple csv files at once. 
https://imperiallondon-my.sharepoint.com/:u:/r/personal/jjo11_ic_ac_uk/Documents/CHEPI/research/franco/Health-GPS_SHARED/Health-GPS_INDIA/Visualization/Visualization.R?csf=1&web=1&e=oNcjqB

**Comment by TinyMarsh** [comment]
Thanks @jzhu20 . I wondered if you fancied having a go at creating a pull request so I can review and merge your changes? If you want, we can go through this together perhaps tomorrow? Alternatively, if time is an issue, then I can just do it myself and that's not a problem.

**Comment by jzhu20** [comment]
@TinyMarsh I just created a pull request and added you as reviewer. I'm happy to go through it together. I can make 1-2pm tomorrow, otherwise next Monday from 11am onwards.

**Comment by jamesturner246** [comment]
Could you give a link to the PR? I'll have a look through. Thanks!

**Comment by jzhu20** [comment]
> Could you give a link to the PR? I'll have a look through. Thanks!

https://github.com/imperialCHEPI/healthgps-plots/pull/3
Thanks.

**Comment by jzhu20** [comment]
@TinyMarsh @jamesturner246 
I got this error message when I run 
> Rscript Visualization.R  C:\Users\jzhu5\OneDrive - Imperial College London\Project\RSTL_India\Visualization\From 2023\HealthGPS_Result_S1.csv C:\Users\jzhu5\OneDrive - Imperial College London\Project\RSTL_India\Visualization\From 2023\HealthGPS_Result_S2.csv C:\Users\jzhu5\OneDrive - Imperial College London\Project\RSTL_India\Visualization\From 2023\HealthGPS_Result_S4.csv C:\Users\jzhu5\OneDrive - Imperial College London\Project\RSTL_India\Visualization\From 2023\HealthGPS_Result_S5.csv

collapse 2.0.9, see ?`collapse-package` or ?`collapse-documentation`

Attaching package: 'collapse'

The following object is masked from 'package:stats':

    D

Error in file(file, "rt") : cannot open the connection
Calls: read.csv -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'C:\Users\jzhu5\OneDrive': Permission denied
Execution halted

**Comment by TinyMarsh** [comment]
@jzhu20 it looks like you need to wrap the file locations in quotes.

Try this;
```
Rscript Visualization.R "C:\Users\jzhu5\OneDrive - Imperial College London\Project\RSTL_India\Visualization\From 2023\HealthGPS_Result_S1.csv" "C:\Users\jzhu5\OneDrive - Imperial College London\Project\RSTL_India\Visualization\From 2023\HealthGPS_Result_S2.csv" "C:\Users\jzhu5\OneDrive - Imperial College London\Project\RSTL_India\Visualization\From 2023\HealthGPS_Result_S4.csv" "C:\Users\jzhu5\OneDrive - Imperial College London\Project\RSTL_India\Visualization\From 2023\HealthGPS_Result_S5.csv"
```

OneDrive automatically creates spaces in its directory names which is pretty horrible.
